source.. = src/
output.. = bin/
bin.includes = META-INF/,\
               .,\
               web/,\
               resources/,\
               OSGI-INF/org.openlayer.map.servlet.MapFilter.xml,\
               OSGI-INF/
