source.. = src/
output.. = bin/
bin.includes = META-INF/,\
               .,\
               WEB-INF/,\
               OSGI-INF/org.condast.commons.js.legal.http.LegalServlet.xml,\
               OSGI-INF/org.condast.commons.js.legal.http.LegalWebResources.xml,\
               OSGI-INF/org.condast.commons.js.legal.http.MapFilter.xml,\
               OSGI-INF/
